version: '3'

services:

  vtiger:
    image: javanile/vtiger:7.1.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - .:/app

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql:rw

volumes:
  mysql:
